// Package docs Code generated by swaggo/swag. DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
} = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Social Graph API",
	Description: "A microservice for managing social graph relationships between persons",
}

type s struct{}

func (s *s) ReadDoc() string {
	return ""
}

func init() {
	swag.Register(swag.Name, &s{})
}
